import { Moment } from 'moment';
import { IAtendimentoAssinaturas } from 'app/shared/model/atendimento-assinaturas.model';
import { IDiario } from 'app/shared/model/diario.model';
import { IPacienteDadosCartao } from 'app/shared/model/paciente-dados-cartao.model';
import { IPacienteDiagnostico } from 'app/shared/model/paciente-diagnostico.model';
import { IPacienteDiario } from 'app/shared/model/paciente-diario.model';
import { IPacienteEnqueteApp } from 'app/shared/model/paciente-enquete-app.model';
import { IPacienteOperadora } from 'app/shared/model/paciente-operadora.model';
import { IPacientePedido } from 'app/shared/model/paciente-pedido.model';
import { IPacientePush } from 'app/shared/model/paciente-push.model';
import { IUnidadeEasy } from 'app/shared/model/unidade-easy.model';
import { IFranquia } from 'app/shared/model/franquia.model';
import { ICidade } from 'app/shared/model/cidade.model';
import { IGrauParentesco } from 'app/shared/model/grau-parentesco.model';
import { IProfissional } from 'app/shared/model/profissional.model';
import { IPacienteHospital } from 'app/shared/model/paciente-hospital.model';

export interface IPaciente {
  id?: string;
  senha?: string;
  nome?: string;
  email?: string;
  cpf?: string;
  rg?: string;
  registro?: string;
  nascimento?: Moment;
  sexo?: number;
  telefone?: string;
  telefone2?: string;
  celular?: string;
  celular1?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  uf?: string;
  latitude?: string;
  longitude?: string;
  responsavelFamiliar?: string;
  emailFamiliar?: string;
  cpfFamiliar?: string;
  rgFamiliar?: string;
  nascimentoFamiliar?: Moment;
  sexoFamiliar?: number;
  telefoneFamiliar?: string;
  telefone2Familiar?: string;
  celularFamiliar?: string;
  celular2Familiar?: string;
  cepFamiliar?: string;
  enderecoFamiliar?: string;
  numeroFamiliar?: string;
  complementoFamiliar?: string;
  bairroFamiliar?: string;
  ufFamiliar?: string;
  latitudeFamiliar?: string;
  longitudeFamiliar?: string;
  observacao?: any;
  aph?: number;
  nivelComplexidade?: number;
  passagemPs?: number;
  obsPs?: string;
  passagemInternacao?: number;
  obsInternacao?: string;
  custoTotal?: number;
  observacaoFamiliar?: string;
  mesmoEndereco?: number;
  acessoFamiliar?: number;
  comResponsavel?: number;
  cadastroCompleto?: number;
  ativo?: boolean;
  detalhes?: any;
  liminar?: string;
  expoToken?: string;
  atendimentoAssinaturas?: IAtendimentoAssinaturas[];
  diarios?: IDiario[];
  pacienteDadosCartaos?: IPacienteDadosCartao[];
  pacienteDiagnosticos?: IPacienteDiagnostico[];
  pacienteDiarios?: IPacienteDiario[];
  pacienteEnqueteApps?: IPacienteEnqueteApp[];
  pacienteOperadoras?: IPacienteOperadora[];
  pacientePedidos?: IPacientePedido[];
  pacientePushes?: IPacientePush[];
  unidadeRazaoSocial?: string;
  unidade?: string | any;
  franquiaNomeFantasia?: string;
  franquia?: string | any;
  cidadeDescrCidade?: string;
  cidade?: string | any;
  cidadeFamiliarDescrCidade?: string;
  cidadeFamiliar?: string | any;
  grauParentescoGrauParentesco?: string;
  grauParentesco?: string | any;
  profissionalPrefNome?: string;
  profissionalPref?: string | any;
  tipohospitalServico?: string;
  tipohospital?: string | any;
}

export const defaultValue: Readonly<IPaciente> = {
  ativo: false
};
