import { Moment } from 'moment';

export interface IPaciente {
  id?: number;
  senha?: string;
  nome?: string;
  email?: string;
  cpf?: string;
  rg?: string;
  registro?: string;
  nascimento?: Moment;
  sexo?: number;
  telefone?: string;
  telefone2?: string;
  celular?: string;
  celular1?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  uf?: string;
  latitude?: string;
  longitude?: string;
  responsavelFamiliar?: string;
  emailFamiliar?: string;
  cpfFamiliar?: string;
  rgFamiliar?: string;
  nascimentoFamiliar?: Moment;
  sexoFamiliar?: number;
  telefoneFamiliar?: string;
  telefone2Familiar?: string;
  celularFamiliar?: string;
  celular2Familiar?: string;
  cepFamiliar?: string;
  enderecoFamiliar?: string;
  numeroFamiliar?: string;
  complementoFamiliar?: string;
  bairroFamiliar?: string;
  ufFamiliar?: string;
  latitudeFamiliar?: string;
  longitudeFamiliar?: string;
  observacao?: string;
  aph?: number;
  nivelComplexidade?: number;
  passagemPs?: number;
  obsPs?: string;
  passagemInternacao?: number;
  obsInternacao?: string;
  custoTotal?: number;
  observacaoFamiliar?: string;
  mesmoEndereco?: number;
  acessoFamiliar?: number;
  comResponsavel?: number;
  cadastroCompleto?: number;
  ativo?: number;
  dataPost?: Moment;
  detalhes?: string;
  tipohospital?: number;
  liminar?: string;
  expoToken?: string;
  profissionalPref?: number;
  senhaChat?: string;
  cidadeId?: number;
}

export const defaultValue: Readonly<IPaciente> = {};
