import { Moment } from 'moment';
import { IUnidadeEasy } from 'app/shared/model/unidade-easy.model';
import { IFranquia } from 'app/shared/model/franquia.model';
import { ICidade } from 'app/shared/model/cidade.model';
import { IGrauParentesco } from 'app/shared/model/grau-parentesco.model';
import { IProfissional } from 'app/shared/model/profissional.model';
import { IPacienteHospital } from 'app/shared/model/paciente-hospital.model';

export interface IPaciente {
  id?: string;
  senha?: string;
  nome?: string;
  email?: string;
  cpf?: string;
  rg?: string;
  registro?: string;
  nascimento?: Moment;
  sexo?: number;
  telefone?: string;
  telefone2?: string;
  celular?: string;
  celular1?: string;
  cep?: string;
  endereco?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  uf?: string;
  latitude?: string;
  longitude?: string;
  responsavelFamiliar?: string;
  emailFamiliar?: string;
  cpfFamiliar?: string;
  rgFamiliar?: string;
  nascimentoFamiliar?: Moment;
  sexoFamiliar?: number;
  telefoneFamiliar?: string;
  telefone2Familiar?: string;
  celularFamiliar?: string;
  celular2Familiar?: string;
  cepFamiliar?: string;
  enderecoFamiliar?: string;
  numeroFamiliar?: string;
  complementoFamiliar?: string;
  bairroFamiliar?: string;
  ufFamiliar?: string;
  latitudeFamiliar?: string;
  longitudeFamiliar?: string;
  observacao?: any;
  aph?: number;
  nivelComplexidade?: number;
  passagemPs?: number;
  obsPs?: string;
  passagemInternacao?: number;
  obsInternacao?: string;
  custoTotal?: number;
  observacaoFamiliar?: string;
  mesmoEndereco?: number;
  acessoFamiliar?: number;
  comResponsavel?: number;
  cadastroCompleto?: number;
  ativo?: number;
  detalhes?: any;
  liminar?: string;
  expoToken?: string;
  unidadeRazaoSocial?: string;
  unidade?: string | any;
  franquiaNomeFantasia?: string;
  franquia?: string | any;
  cidadeDescrCidade?: string;
  cidade?: string | any;
  cidadeFamiliarDescrCidade?: string;
  cidadeFamiliar?: string | any;
  grauParentescoGrauParentesco?: string;
  grauParentesco?: string | any;
  profissionalPrefNome?: string;
  profissionalPref?: string | any;
  tipohospitalServico?: string;
  tipohospital?: string | any;
}

export const defaultValue: Readonly<IPaciente> = {};
