import { Moment } from 'moment';
import { IDiario } from 'app/shared/model/diario.model';
import { IPacienteDiario } from 'app/shared/model/paciente-diario.model';
import { IUnidadeEasy } from 'app/shared/model/unidade-easy.model';
import { ITipoUsuario } from 'app/shared/model/tipo-usuario.model';

export interface IUsuario {
  id?: string;
  idOperadora?: string;
  senha?: string;
  nome?: string;
  email?: string;
  telefone?: string;
  celular?: string;
  cpf?: string;
  rg?: string;
  sexo?: number;
  nascimento?: Moment;
  verAtendimento?: boolean;
  cadAtendimento?: boolean;
  ediAtendimento?: boolean;
  baixaManualAtendimento?: boolean;
  delAtendimento?: boolean;
  relAtendimento?: boolean;
  verPad?: boolean;
  cadPad?: boolean;
  ediPad?: boolean;
  delPad?: boolean;
  relPad?: boolean;
  verDiario?: boolean;
  cadDiario?: boolean;
  ediDiario?: boolean;
  delDiario?: boolean;
  relDiario?: boolean;
  verCategoria?: boolean;
  cadCategoria?: boolean;
  ediCategoria?: boolean;
  delCategoria?: boolean;
  verEspecialidade?: boolean;
  cadEspecialidade?: boolean;
  ediEspecialidade?: boolean;
  delEspecialidade?: boolean;
  relEspecialidade?: boolean;
  verEspecialidadeValor?: boolean;
  cadEspecialidadeValor?: boolean;
  ediEspecialidadeValor?: boolean;
  delEspecialidadeValor?: boolean;
  relEspecialidadeValor?: boolean;
  verOperadora?: boolean;
  cadOperadora?: boolean;
  ediOperadora?: boolean;
  delOperadora?: boolean;
  verPaciente?: boolean;
  cadPaciente?: boolean;
  ediPaciente?: boolean;
  delPaciente?: boolean;
  relPaciente?: boolean;
  verProfissional?: boolean;
  cadProfissional?: boolean;
  ediProfissional?: boolean;
  delProfissional?: boolean;
  ativProfissional?: boolean;
  relProfissional?: boolean;
  verPush?: boolean;
  cadPushPaciente?: boolean;
  cadPushProfissional?: boolean;
  verTermoPaciente?: boolean;
  ediTermoPaciente?: boolean;
  verTermoProfissional?: boolean;
  ediTermoProfissional?: boolean;
  verOutros?: boolean;
  cadOutros?: boolean;
  ediOutros?: boolean;
  delOutros?: boolean;
  relOutros?: boolean;
  verUnidadeEasy?: boolean;
  cadUnidadeEasy?: boolean;
  ediUnidadeEasy?: boolean;
  delUnidadeEasy?: boolean;
  verUsuario?: boolean;
  cadUsuario?: boolean;
  ediUsuario?: boolean;
  delUsuario?: boolean;
  verPtaResultado?: boolean;
  cadPtaResultado?: boolean;
  delPtaResultado?: boolean;
  verPtaAtividade?: boolean;
  cadPtaAtividade?: boolean;
  delPtaAtividade?: boolean;
  permissaoUsuario?: boolean;
  verProntuario?: boolean;
  cadProntuario?: boolean;
  ediProntuario?: boolean;
  delProntuario?: boolean;
  delProntuarioFoto?: boolean;
  valoresFinanceiro?: boolean;
  autorizacaoValorFinanceiro?: boolean;
  confirmarPagamentoFinanceiro?: boolean;
  gerenciarSorteios?: boolean;
  envioRecusa?: boolean;
  envioIntercorrencia?: boolean;
  envioCancelamento?: boolean;
  envioAvaliacao?: boolean;
  envioPedido?: boolean;
  alertaAtendimento?: boolean;
  ativo?: boolean;
  envioGlosado?: boolean;
  emergencia?: boolean;
  token?: boolean;
  editAtendimento?: boolean;
  ouvirLigacao?: boolean;
  verPainelIndicadores?: boolean;
  prorrogarPad?: boolean;
  cancelarAtendMassa?: boolean;
  cadMatMed?: boolean;
  ediMatMed?: boolean;
  delMatMed?: boolean;
  verColPta?: boolean;
  verColFoto?: boolean;
  verColLc?: boolean;
  verAtendCancelado?: boolean;
  verAtendAgConfirmacao?: boolean;
  ediGeoLocalizacaoAtendimento?: boolean;
  copiarEvolucao?: boolean;
  copiarNomeProf?: boolean;
  copiarRegistroProf?: boolean;
  idAreaAtuacao?: string;
  diarios?: IDiario[];
  pacienteDiarios?: IPacienteDiario[];
  unidadeRazaoSocial?: string;
  unidade?: string | any;
  tipoUsuario?: string | any;
}

export const defaultValue: Readonly<IUsuario> = {
  verAtendimento: false,
  cadAtendimento: false,
  ediAtendimento: false,
  baixaManualAtendimento: false,
  delAtendimento: false,
  relAtendimento: false,
  verPad: false,
  cadPad: false,
  ediPad: false,
  delPad: false,
  relPad: false,
  verDiario: false,
  cadDiario: false,
  ediDiario: false,
  delDiario: false,
  relDiario: false,
  verCategoria: false,
  cadCategoria: false,
  ediCategoria: false,
  delCategoria: false,
  verEspecialidade: false,
  cadEspecialidade: false,
  ediEspecialidade: false,
  delEspecialidade: false,
  relEspecialidade: false,
  verEspecialidadeValor: false,
  cadEspecialidadeValor: false,
  ediEspecialidadeValor: false,
  delEspecialidadeValor: false,
  relEspecialidadeValor: false,
  verOperadora: false,
  cadOperadora: false,
  ediOperadora: false,
  delOperadora: false,
  verPaciente: false,
  cadPaciente: false,
  ediPaciente: false,
  delPaciente: false,
  relPaciente: false,
  verProfissional: false,
  cadProfissional: false,
  ediProfissional: false,
  delProfissional: false,
  ativProfissional: false,
  relProfissional: false,
  verPush: false,
  cadPushPaciente: false,
  cadPushProfissional: false,
  verTermoPaciente: false,
  ediTermoPaciente: false,
  verTermoProfissional: false,
  ediTermoProfissional: false,
  verOutros: false,
  cadOutros: false,
  ediOutros: false,
  delOutros: false,
  relOutros: false,
  verUnidadeEasy: false,
  cadUnidadeEasy: false,
  ediUnidadeEasy: false,
  delUnidadeEasy: false,
  verUsuario: false,
  cadUsuario: false,
  ediUsuario: false,
  delUsuario: false,
  verPtaResultado: false,
  cadPtaResultado: false,
  delPtaResultado: false,
  verPtaAtividade: false,
  cadPtaAtividade: false,
  delPtaAtividade: false,
  permissaoUsuario: false,
  verProntuario: false,
  cadProntuario: false,
  ediProntuario: false,
  delProntuario: false,
  delProntuarioFoto: false,
  valoresFinanceiro: false,
  autorizacaoValorFinanceiro: false,
  confirmarPagamentoFinanceiro: false,
  gerenciarSorteios: false,
  envioRecusa: false,
  envioIntercorrencia: false,
  envioCancelamento: false,
  envioAvaliacao: false,
  envioPedido: false,
  alertaAtendimento: false,
  ativo: false,
  envioGlosado: false,
  emergencia: false,
  token: false,
  editAtendimento: false,
  ouvirLigacao: false,
  verPainelIndicadores: false,
  prorrogarPad: false,
  cancelarAtendMassa: false,
  cadMatMed: false,
  ediMatMed: false,
  delMatMed: false,
  verColPta: false,
  verColFoto: false,
  verColLc: false,
  verAtendCancelado: false,
  verAtendAgConfirmacao: false,
  ediGeoLocalizacaoAtendimento: false,
  copiarEvolucao: false,
  copiarNomeProf: false,
  copiarRegistroProf: false
};
